### ISSUE TITLE
move to organization

### ISSUE THREAD

**Issue by larsbuntemeyer** [climate-service-center/index_calculator#44]
we should move this to: https://github.com/climate-service-center

@ludwiglierhammer if you accept my invitation to climate-service-center, you should be able to move this repo to that organization (only you as the owner can do that (under settings) and you need to be a member of the target organization).  I think that would be the smootest way to also guarantee that your contributions stay visible in the future.

Please also feel free to move other repos, e.g. xweights and pyhomogenize if you want!

**Comment by larsbuntemeyer** [comment]
I will take care to update tokens for pypi and readthedocs...

**Comment by ludwiglierhammer** [comment]
Hi @larsbuntemeyer , I moved `index_calculator`, `pyhomogenize` and `xweights` to organization climate-service-center.

**Comment by larsbuntemeyer** [comment]
Thanks, i'll update the links on readthedocs!
