### ISSUE TITLE
Two different licenses

### ISSUE THREAD

**Issue by ludwiglierhammer** [climate-service-center/index_calculator#50]
``index_calculator`` is published under two different licenses.

* [pypi](https://pypi.org/project/index-calculator/):  [MIT license](https://github.com/climate-service-center/index_calculator/blob/main/LICENSE)
* [zenodo](https://zenodo.org/records/10159231): [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode) is [not recommended](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) to use on software.

I think we should consider changing the license on zenodo.

``pyhomogenize`` has the same issue.

**Comment by larsbuntemeyer** [comment]
Thanks! I think we should add a `.zenodo.json` configuration, e.g.
```json
{
  "creators": [
    {
      "affiliation": "Helmholtz-Zentrum Hereon",
      "name": "Lars Buntemeyer",
      "orcid": "0000-0002-0849-2404"
    }
  ],
  "keywords": [
    "xclim",
    "xarray",
    "climate indicator"
  ],
  "license": "MIT",
  "upload_type": "software",
  "access_right": "open"
}
```

**Comment by ludwiglierhammer** [comment]
I think this would solve the issue. Would you add the file?
